# Database configurations

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezine=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  spring-doc:
    paths-to-match:
      - /api/**/v1/**
    swagger-ui:
      use-root-path: true